from typing import Any

class Border:
    color: Any
    width: tuple[int, int, int, int]
    def __init__(self, color:str, *args:int) -> None: ...

    @property
    def top(self) -> int: ...
    @property
    def right(self) -> int: ...
    @property
    def bottom(self) -> int: ...
    @property
    def left(self) -> int: ...